@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Пользователь" as user
participant "KiloService" as service
participant "AB: Visary" as visary

user -> service: Загрузить файл с данными
service -> service: Получить файл типа xlsx
service -> service: Определить, какие листы есть в файле
alt Если листы есть
    service -> service: Зафиксировать количество листов для обработки
else Если листов нет
    service -x service: Вернуть предупреждение о некорректном файле
    service --> user: Ошибка при загрузке
end
loop Для каждого листа из xlsx файла
    service -> service: Определить наличие колонок из заданного списка
    note left: Колонок может быть меньше, чем в эталонном файле
    alt Если обязательные (какие??) колонки из спика есть
        service -> service: Зафиксировать маппинг между названиями колонок и ячейками в файле
    else Если обязательные колонки отсутствуют
        service -x service: Вернуть предупреждение о некорректном файле
        service --> user: Ошибка при загрузке
        service -> service: Перейти к следующему листу
    end
    loop Для каждой строчки на листе
        service -> service: Получить значение из полей для поиска Объекта (РНС, НПС, Этап)
        alt Если (РНС, НПС, Этап) значения отличаются от предыдущей итерации
            service -> visary: Найти Объект строительства тремя способами \n (РНС + Этап / РНС + НПС + Этап / НПС + Этап)
            service -> visary: После первого положительного ответа - Запомнить id Объекта
            alt Ели в Объекте нет РНС
                service -> visary: Обновить значение РНС в Объекте строительства
            else Если в Объекте нет Застройщика
                service -> visary: Найти Организацию по ПИНу застройщика из ячейки
                alt Если Организация не найдена
                    service -> service: Перейти к поиску Секции
                end
                service -> visary: Запомнить id Организации
                service -> visary: Добавить в Участники Объекта найденную Организацию с ролью Застройщик
            end
            service -> service: Перейти в поиск Секции
        else Если значений нет
            service -x service: Вернуть предупреждение о некорректном файле, перейти к следующей строке
            note left: как определим конец файла?
        end
        service -> visary: Получить наименование Секции из ячейки
        note left: уточнить о наименовании секции на листе,\n но логичнее было бы указывать номера только в ячейках
        service -> visary: Определить числовую часть наименования \n(Если написано "Лит 1.1" оставить только 1.1)
        service -> visary: Найти секцию по наименованию из ячейки
        alt Если секция не найдена
            service -> visary: Создать секцию по наименованию
            note left: откуда будем знать, какой тип у секции?
        end
        service -> service: Запомнить id Секции
        service -> service: Получить значения для поиска Помещения
        service -> visary: Найти Помещение
        alt Если Помещение найдено
            service -> service: Перейти к поиску ДДУ для Помещения
            service -> service: (или надо обновить Помещение?)
        else Если помещение не найдено
            service -> service: Создать Помещение
        else

        service -> visary: Найти ДДУ
        alt Если ДДУ найдено
            service -> service: (или надо обновить ДДУ?)
        else Если ДДУ не найдено
            service -> service: Создать ДДУ
        else

        service -> visary: Перейти к следующей строке
    end
    service -> visary: Перейти к следующему листу
end

@enduml