// <auto-generated />
using System;
using KiloImportService.Api.Data.Visary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KiloImportService.Api.Migrations.Visary
{
    [DbContext(typeof(VisaryDbContext))]
    [Migration("20260623053617_InitialDataSchema")]
    partial class InitialDataSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KiloImportService.Api.Data.Visary.Entities.ConstructionProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean")
                        .HasColumnName("Hidden");

                    b.Property<string>("IdentifierKK")
                        .HasColumnType("text")
                        .HasColumnName("IdentifierKK");

                    b.Property<string>("IdentifierZPLM")
                        .HasColumnType("text")
                        .HasColumnName("IdentifierZPLM");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("ConstructionProject", "Data");
                });

            modelBuilder.Entity("KiloImportService.Api.Data.Visary.Entities.ConstructionSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("Address");

                    b.Property<string>("ConstructionPermissionNumber")
                        .HasColumnType("text")
                        .HasColumnName("ConstructionPermissionNumber");

                    b.Property<int?>("ConstructionProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("ConstructionProjectID");

                    b.Property<string>("ConstructionProjectNumber")
                        .HasColumnType("text")
                        .HasColumnName("ConstructionProjectNumber");

                    b.Property<int?>("FinishingMaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("FinishingMaterialId");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean")
                        .HasColumnName("Hidden");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("RegionID");

                    b.Property<string>("StageNumber")
                        .HasColumnType("text")
                        .HasColumnName("StageNumber");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.Property<int?>("TownId")
                        .HasColumnType("integer")
                        .HasColumnName("TownID");

                    b.Property<DateTime?>("Version")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("ConstructionSite", "Data");
                });

            modelBuilder.Entity("KiloImportService.Api.Data.Visary.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingSection")
                        .HasColumnType("text")
                        .HasColumnName("BuildingSection");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("Cost");

                    b.Property<decimal?>("CostForOne")
                        .HasColumnType("numeric")
                        .HasColumnName("CostForOne");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("ExplicationNumber")
                        .HasColumnType("text")
                        .HasColumnName("ExplicationNumber");

                    b.Property<string>("Floor")
                        .HasColumnType("text")
                        .HasColumnName("Floor");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean")
                        .HasColumnName("Hidden");

                    b.Property<string>("IsSeparateEntrance")
                        .HasColumnType("text")
                        .HasColumnName("IsSeparateEntrance");

                    b.Property<string>("IsShowcaseWindows")
                        .HasColumnType("text")
                        .HasColumnName("IsShowcaseWindows");

                    b.Property<bool>("IsStudio")
                        .HasColumnType("boolean")
                        .HasColumnName("IsStudio");

                    b.Property<int>("KindId")
                        .HasColumnType("integer")
                        .HasColumnName("KindID");

                    b.Property<double?>("LivingArea")
                        .HasColumnType("double precision")
                        .HasColumnName("LivingArea");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasColumnName("Number");

                    b.Property<string>("ParkingPlaceType")
                        .HasColumnType("text")
                        .HasColumnName("ParkingPlaceType");

                    b.Property<double>("ProjectArea")
                        .HasColumnType("double precision")
                        .HasColumnName("ProjectArea");

                    b.Property<string>("RoomPurpose")
                        .HasColumnType("text")
                        .HasColumnName("RoomPurpose");

                    b.Property<int?>("RoomsNumber")
                        .HasColumnType("integer")
                        .HasColumnName("RoomsNumber");

                    b.Property<int?>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("SectionID");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("SiteID");

                    b.Property<double?>("SummerRoomArea")
                        .HasColumnType("double precision")
                        .HasColumnName("SummerRoomArea");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.Property<double?>("TotalArea")
                        .HasColumnType("double precision")
                        .HasColumnName("TotalArea");

                    b.Property<double?>("TotalAreaWithoutSummerRoom")
                        .HasColumnType("double precision")
                        .HasColumnName("TotalAreaWithoutSummerRoom");

                    b.Property<string>("UniqueNumber")
                        .HasColumnType("text")
                        .HasColumnName("UniqueNumber");

                    b.HasKey("Id");

                    b.ToTable("Room", "Data");
                });

            modelBuilder.Entity("KiloImportService.Api.Data.Visary.Entities.RoomKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean")
                        .HasColumnName("Hidden");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("RoomKind", "Data");
                });
#pragma warning restore 612, 618
        }
    }
}
