# Генерирует C# DTO-классы из метаданных visary_api.fields.
# Источник правды — таблица visary_api.fields в Postgres.
# Перезапускать после нового снэпшота API (audit-visary-api.ps1 + import-visary-audit.ps1).

[CmdletBinding()]
param(
    [string] $InputFile = '.audit/all_top_fields.psv',
    [string] $OutDir    = 'Visary.Api.Client/Dto/Generated'
)

$ErrorActionPreference = 'Stop'

# Маппинг: имя сущности (mnemonic) → C# class name суффикс.
$classNames = @{
    'constructionproject'            = 'ConstructionProjectFull'
    'constructionsite'               = 'ConstructionSiteFull'
    'constructionsection'            = 'ConstructionSectionFull'
    'constructionsiteindicator'      = 'ConstructionSiteIndicatorFull'
    'constructionsiteindicatorvalue' = 'ConstructionSiteIndicatorValueFull'
    'room'                           = 'RoomFull'
    'cadastralarea'                  = 'CadastralAreaFull'
    'percentbet'                     = 'PercentBetFull'
    'shareagreement'                 = 'ShareAgreementFull'
    'deal'                           = 'DealFull'
    'organization'                   = 'OrganizationFull'
    # справочники — без суффикса Full, потому что других DTO для них нет
    'town'                           = 'TownRaw'
    'region'                         = 'RegionRaw'
    'projecttype'                    = 'ProjectTypeRaw'
    'inflationcalcmethod'            = 'InflationCalcMethodRaw'
    'estateclass'                    = 'EstateClassRaw'
    'buildingmaterial'               = 'BuildingMaterialRaw'
    'finishingmaterial'              = 'FinishingMaterialRaw'
    'roomkind'                       = 'RoomKindRaw'
}

# Поля, для которых тип в snapshot — null. Подсказки на основе имени поля.
function Resolve-NullType([string] $fieldName) {
    if ($fieldName -match '(Id|ID|PIN|Number|Year|Quantity|Count|Sum|Cost|Rate|Area|Length|Width|Height|Stage)$') { return 'double?' }
    if ($fieldName -match '(Date|StartDate|EndDate|Time)$') { return 'string?' }
    if ($fieldName -match '^(Is|Has)') { return 'bool?' }
    return 'string?'
}

function CSharp-Type([string] $fieldName, [string] $dataType) {
    switch ($dataType) {
        'string'   { return 'string?' }
        'datetime' {
            if ($fieldName -in @('Version','ModifiedAt','DateCreate','LastUpdate','CreatedAt','UpdatedAt')) {
                return 'DateTime?'
            }
            return 'string?'
        }
        'int'      {
            if ($fieldName -eq 'ID')         { return 'int' }
            if ($fieldName -eq 'RowVersion') { return 'long' }
            return 'int?'
        }
        'long'     { return 'long?' }
        'double'   { return 'double?' }
        'boolean'  { return 'bool?' }
        'ref'      { return 'VisaryRef?' }
        'array'    {
            if ($fieldName -eq 'UseTypes') { return 'List<CadastralUseTypeRef>?' }
            return 'List<JsonElement>?'
        }
        'object'   {
            if ($fieldName -eq 'Location') { return 'VisaryLocation?' }
            if ($fieldName -eq 'CurrentUser') { return 'VisaryCurrentUser?' }
            # Deal в percentbet идёт как {ID, Hidden} — фактически VisaryRef без Title
            return 'VisaryRef?'
        }
        'null'     { return Resolve-NullType $fieldName }
        default    { return 'JsonElement?' }
    }
}

# ─── Группируем поля по мнемоникам ───
$rows = Get-Content $InputFile | Where-Object { $_ } | ForEach-Object {
    $p = $_.Split('|', 3)
    [pscustomobject]@{ Mnemonic=$p[0]; Field=$p[1]; Type=$p[2] }
}
$grouped = $rows | Group-Object Mnemonic

New-Item -ItemType Directory -Path $OutDir -Force | Out-Null

# ─── Генерация классов ───
foreach ($g in $grouped) {
    $mnemonic  = $g.Name
    $className = $classNames[$mnemonic]
    if (-not $className) { Write-Warning "skip unknown mnemonic '$mnemonic'"; continue }

    $sb = New-Object System.Text.StringBuilder
    [void] $sb.AppendLine('// <auto-generated />')
    [void] $sb.AppendLine('// Сгенерировано scripts/generate-visary-dtos.ps1 из visary_api.fields.')
    [void] $sb.AppendLine("// Источник: GET /api/visary/crud/$mnemonic/{id}")
    [void] $sb.AppendLine('// Не редактируйте вручную — изменения будут затёрты следующим запуском генератора.')
    [void] $sb.AppendLine('using System.Text.Json;')
    [void] $sb.AppendLine('')
    [void] $sb.AppendLine('namespace Visary.Api.Dto;')
    [void] $sb.AppendLine('')
    [void] $sb.AppendLine("public sealed class $className")
    [void] $sb.AppendLine('{')

    # Сначала ID и Title, потом остальное в алфавитном порядке (как уже отсортировано в SQL).
    foreach ($f in $g.Group) {
        # Пропускаем служебные ассоциации, если они вдруг попали в response_body
        if ($f.Field -match '^A_(O2O|O2M|M2M)_') { continue }
        $cs = CSharp-Type $f.Field $f.Type
        [void] $sb.AppendLine("    public $cs $($f.Field) { get; set; }")
    }
    [void] $sb.AppendLine('}')

    $outFile = Join-Path $OutDir "$className.cs"
    $sb.ToString() | Out-File -FilePath $outFile -Encoding utf8
    Write-Host ("  + {0,-40} → {1} ({2} fields)" -f $mnemonic, $className, $g.Group.Count)
}

# ─── Вспомогательные DTO (общие, не сгенерированы) ───
$shared = @'
// <auto-generated />
// Вспомогательные DTO для вложенных объектов в ответах Visary.
// Сгенерировано scripts/generate-visary-dtos.ps1.
namespace Visary.Api.Dto;

public sealed class VisaryLocation
{
    public string? Address { get; set; }
    public string? Disposition { get; set; }
    public double BoundMinX { get; set; }
    public double BoundMinY { get; set; }
    public double BoundMaxX { get; set; }
    public double BoundMaxY { get; set; }
    public bool HasBounds { get; set; }
    public double CenterPointX { get; set; }
    public double CenterPointY { get; set; }
    public bool HasCenterPoint { get; set; }
    public string? Cluster { get; set; }
    public int ZoomLevel { get; set; }
}

public sealed class VisaryCurrentUser
{
    public string? AvatarUrl { get; set; }
    public string? Title { get; set; }
    public int ID { get; set; }
    public bool Hidden { get; set; }
}
'@
$shared | Out-File -FilePath (Join-Path $OutDir 'VisarySharedDtos.cs') -Encoding utf8

Write-Host ""
Write-Host "Generated $($grouped.Count) entity DTOs + shared DTOs in $OutDir"
