-- Авто-сгенерировано scripts/generate-visary-ddl.mjs из Context/schema_export.csv
-- Дата: 2026-04-28T10:36:51.551Z
-- Включено таблиц: 66 (из 360)

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

CREATE SCHEMA IF NOT EXISTS "Base";
CREATE SCHEMA IF NOT EXISTS "Data";

-- ═══════════════════════ Schema: Base ═══════════════════════

CREATE TABLE IF NOT EXISTS "Base"."User" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "AvatarUrl" text,
    "Title" character varying(255),
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Base"."UserGroup" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "AvatarUrl" text,
    "IsSystem" boolean NOT NULL,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_UserGroup" PRIMARY KEY ("ID")
);

-- ═══════════════════════ Schema: Data ═══════════════════════

CREATE TABLE IF NOT EXISTS "Data"."AcceptedContract" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "WBSContractID" integer,
    "ClosureDocumentID" integer,
    "Title" text,
    "Sum" numeric NOT NULL,
    "DateUpdate" date,
    "Status" integer NOT NULL,
    "ContractID" integer NOT NULL,
    "ReportingPeriod" text,
    "Quantity" double precision,
    "UnitID" integer,
    "PaymentID" integer,
    "Version" timestamp with time zone,
    "Color" text,
    "DuplicateColor" text,
    "Verified" boolean NOT NULL,
    "Comment" text,
    "Hidden" boolean NOT NULL,
    "PlanMonth" integer NOT NULL,
    "PlanQuarter" integer NOT NULL,
    "PlanYear" integer NOT NULL,
    CONSTRAINT "PK_AcceptedContract" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."AddAgreement" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ContractID" integer,
    "Date" date,
    "Sum" numeric,
    "Files" text,
    "Status" integer NOT NULL,
    "ProjectDocID" integer,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_AddAgreement" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."AdditionalPropertiesConfig" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_AdditionalPropertiesConfig" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."AnalogCriteria" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "ConstructionSiteID" integer,
    "IsTown" boolean NOT NULL,
    "IsRegion" boolean NOT NULL,
    "IsEstateClass" boolean NOT NULL,
    "IsFinishingMaterial" boolean NOT NULL,
    "IsBuildingMaterial" boolean NOT NULL,
    "IsType" boolean NOT NULL,
    "FinishPeriod_Start" date,
    "FinishPeriod_End" date,
    "AnalogStartPriceResidental" numeric,
    "AnalogFinishPriceResidental" numeric,
    "AnalogSalesResidentalQuarter" numeric,
    "AnalogPriceNonResidental" numeric,
    "AnalogPriceParking" numeric,
    "AnalogPriceOtherNonResidental" numeric,
    "AnalogPriceParkingUnit" numeric,
    "IsCommissioning" boolean,
    "RoomCategory" integer,
    "AnalogSearchRadious" integer,
    "CalculateDate" date,
    "AnalogSalesResidentalPercent" double precision,
    "AnalogPhotoLocation" text,
    "ReportFiles" text,
    "FinishingStartPeriod" date,
    "FinishingEndPeriod" date,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_AnalogCriteria" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Analysis" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "AuditID" integer,
    "Title" text,
    "DocFullPackage" integer,
    "TableNum" character varying(255),
    "TableName" text,
    "Result" text,
    "Date" date,
    "AnalysisType" integer NOT NULL,
    "Status" integer NOT NULL,
    "AuthorID" integer,
    "ResponsibleID" integer,
    "Files" text,
    "ProjectID" integer,
    "Group" integer,
    "Compliance" integer,
    "SortOrder" integer NOT NULL,
    "Comment" text,
    "DegreeOfReadiness" double precision,
    "Color" text,
    "Version" timestamp with time zone,
    "ReportFiles" text,
    "AnalysisStatus" integer,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_Analysis" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."AreaDocument" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Comment" text,
    "ProjectDocID" integer,
    "AnalysisID" integer,
    "TerritoryZone" text,
    "UseTypeConditionalID" integer,
    "Organisation" text,
    "IssuedTo" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_AreaDocument" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."BuildingMaterial" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" character varying(4),
    "CurrentUserID" integer,
    "Version" timestamp with time zone,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_BuildingMaterial" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."CadastralArea" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Area" double precision NOT NULL,
    "UnstructuredArea" text,
    "CadastralEngineer" text,
    "CadastralNum" character varying(255),
    "LandCategoryID" integer,
    "LandWork" text,
    "LandWorkDate" text,
    "PLanArea" text,
    "InitRightRestrictionTypeID" integer,
    "Version" timestamp with time zone,
    "Description" text,
    "Address" text,
    "FactUseTypeAreaID" integer,
    "CadastralCost" numeric,
    "Owner" text,
    "Encumbrance" text,
    "SpecialMarks" text,
    "MarketCost" numeric,
    "Discount" double precision,
    "CollateralValue" numeric,
    "EGRNDate" date,
    "EGRNNumber" text,
    "FullyPaid" boolean NOT NULL,
    "Surveying" boolean NOT NULL,
    "NotReady" boolean NOT NULL,
    "Vendor" text,
    "IsVendorAffiliate" boolean NOT NULL,
    "ExternalVendor" boolean NOT NULL,
    "RentalPrice" numeric,
    "OldRegistrationNumber" text,
    "RelevanceStatus" text,
    "PersonDataAvail" text,
    "NoConsentThirdParty" text,
    "CourtRequirements" text,
    "ObjectionsToRight" text,
    "DecisionToWithdraw" text,
    "PersonInvolvement" text,
    "StatementBacklog" text,
    "FailureToRegister" text,
    "InCount" boolean NOT NULL,
    "Queues" text,
    "Hidden" boolean NOT NULL,
    "SysAllParents" text,
    "SortOrder" double precision NOT NULL,
    "ParentID" integer,
    "AreaDocumentID" integer,
    CONSTRAINT "PK_CadastralArea" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Chapter" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Status" integer NOT NULL,
    "ChapterNum" text,
    "Weight" double precision NOT NULL,
    "Version" timestamp with time zone,
    "Code" character varying(4),
    "CurrentUserID" integer,
    "Hidden" boolean NOT NULL,
    "SysAllParents" text,
    "SortOrder" double precision NOT NULL,
    "ParentID" integer,
    "Title" character varying(500),
    CONSTRAINT "PK_Chapter" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."CheckList" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "SubmittedDocumentsID" integer,
    "Title" text,
    "ProjectID" integer,
    "SiteID" integer,
    "ResponsibleID" integer,
    "Comment" text,
    "Status" integer NOT NULL,
    "Version" timestamp with time zone,
    "Errors" text,
    "Subject" text,
    "Message" text,
    "Files" text,
    "Deadline" integer NOT NULL,
    "ReportFiles" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_CheckList" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."ClientData" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "QuarterRatesPricesID" integer,
    "SiteRatesPricesID" integer,
    "Stage" integer,
    "PeriodStartDate" date,
    "ResidentialRates" double precision,
    "ResidentialCost" numeric,
    "NonresidentialRates" double precision,
    "NonresidentialCost" numeric,
    "OthernonresidentialRates" double precision,
    "OtherNonresidentialCost" numeric,
    "ParkingRates" double precision,
    "ParkingCost" numeric,
    "Date" date,
    "SiteID" integer,
    "ODCountRes" integer,
    "ODCountNonRes" integer,
    "ODCountOtherNonRes" integer,
    "ODCountParking" integer,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_ClientData" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."ClientSegment" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Code" text,
    "ModifiedByID" integer,
    "ModifiedAt" timestamp with time zone NOT NULL,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_ClientSegment" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."ClosureDocument" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Number" text,
    "ContractID" integer,
    "DocDate" date NOT NULL,
    "Status" integer,
    "ProjectDocID" integer,
    "Organization" text,
    "Version" timestamp with time zone,
    "Files" text,
    "ClosingSum" numeric NOT NULL,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_ClosureDocument" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."CompanyGroup" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Code" character varying(4),
    "FrozenProjects" boolean NOT NULL,
    "ViolationProjectTimeline" boolean NOT NULL,
    "ClaimsExistance" boolean NOT NULL,
    "LawSuitsExistance" boolean NOT NULL,
    "UnfinishedExistance" boolean NOT NULL,
    "Experienced" boolean NOT NULL,
    "Status" integer NOT NULL,
    "Version" timestamp with time zone,
    "ExperienceList" text,
    "Conclusions" text,
    "CreditPortfolio" boolean NOT NULL,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_CompanyGroup" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."ConstructionSection" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" character varying(255),
    "ConstructionSiteID" integer,
    "TypeID" integer,
    "Stage" integer NOT NULL,
    "HasUndergroundStage" boolean NOT NULL,
    "Description" text,
    "HasLift" boolean NOT NULL,
    "ResQuantity" integer,
    "NonresQuantity" integer,
    "OtherNonresQuantity" integer,
    "ParkingQuantity" integer,
    "ResProjectArea" double precision,
    "ResAreaWithoutSummerRoom" double precision,
    "NonresArea" double precision,
    "OtherNonresArea" double precision,
    "ParkingArea" double precision,
    "AvgResArea" double precision,
    "AvgResAreaWithoutSummerRoom" double precision,
    "ResPercentage" double precision,
    "SectionID" integer,
    "ClaimedCost" numeric,
    "BuildingMaterialID" integer,
    "CostPerUnit" numeric,
    "TotalCost" numeric,
    "Hidden" boolean NOT NULL,
    "Version" timestamp with time zone,
    CONSTRAINT "PK_ConstructionSection" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."ConstructionSite_Queues" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OwnerID" integer NOT NULL,
    "ObjectID" integer NOT NULL,
    CONSTRAINT "PK_ConstructionSite_Queues" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."ConstructionType" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" character varying(4),
    "CurrentUserID" integer,
    "Version" timestamp with time zone,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ConstructionType" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Contract" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "ProjectID" integer NOT NULL,
    "Status" integer NOT NULL,
    "Description" text,
    "ContractNumber" character varying(255),
    "ContractDate" date,
    "Sum" numeric NOT NULL,
    "SumType" integer NOT NULL,
    "FinalSum" numeric NOT NULL,
    "PreviousID" integer,
    "ProviousID" integer,
    "Customer" text,
    "Contractor" text,
    "INN" text,
    "ReportingPeriod" text,
    "DateUpdate" date,
    "ContractCurrencyID" integer,
    "ContractFile" text,
    "ClientID" text,
    "Type" integer NOT NULL,
    "ProjectDocID" integer,
    "Color" text,
    "NumberDate" text,
    "Hidden" boolean NOT NULL,
    "Version" timestamp with time zone,
    CONSTRAINT "PK_Contract" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."ContractCurrency" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" character varying(4),
    "CurrentUserID" integer,
    "NumCode" integer NOT NULL,
    "Country" character varying(255),
    "Version" timestamp with time zone,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ContractCurrency" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."DocSubType" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "DocClass" integer NOT NULL,
    "ChapterID" integer,
    "Code" character varying(4),
    "CurrentUserID" integer,
    "File" text,
    "Version" timestamp with time zone,
    "ShortTitle" character varying(50),
    "Status" integer NOT NULL,
    "AuthorID" integer,
    "CheckListDisable" boolean NOT NULL,
    "ProjectStage" integer,
    "ImportType" integer,
    "Hidden" boolean NOT NULL,
    "SysAllParents" text,
    "SortOrder" double precision NOT NULL,
    "ParentID" integer,
    "Title" character varying(500),
    CONSTRAINT "PK_DocSubType" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."EscrowAccount" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Office" text,
    "Number" text,
    "SignOfTroubleID" integer,
    "StatusID" integer,
    "CurrentBalance" numeric,
    "AvailableBalance" numeric,
    "ReserveAmount" numeric,
    "DepositorPIN" text,
    "DepositorINN" text,
    "DepositorFullName" text,
    "OpeningDate" date,
    "ClosingDate" date,
    "DepositingTerm" text,
    "AccountingMode" integer,
    "DepositingAmount" numeric,
    "Type" text,
    "Group" text,
    "ContractCurrencyID" integer,
    "StartDate" date,
    "DepositingHoldNumber" text,
    "FundsHoldNumber" text,
    "ConstructionProjectNumber" text,
    "ReservationDate" date,
    "IsIncompleteOpen" boolean NOT NULL,
    "RoomKind" text,
    "ProjectNumber" text,
    "StageNumber" text,
    "HouseNumberPermit" text,
    "HouseNumber" text,
    "ConditionalNumber" text,
    "SiteID" integer,
    "ProjectID" integer,
    "RoomID" integer,
    "ValidityStatus" integer,
    "RoomKindRefID" integer,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_EscrowAccount" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."EscrowAccount_SlaveObject" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Date" date,
    "Amount" numeric,
    "IncomingBalance" numeric,
    "OutcomingBalance" numeric,
    "OwnerID" integer NOT NULL,
    "SortOrder" double precision NOT NULL,
    CONSTRAINT "PK_EscrowAccount_SlaveObject" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."EscrowAccountStatus" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Code" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_EscrowAccountStatus" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."EstateClass" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" character varying(4),
    "CurrentUserID" integer,
    "Version" timestamp with time zone,
    "BaseFinishingCost" numeric NOT NULL,
    "HasLift" boolean NOT NULL,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_EstateClass" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."EstateObject" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "CadastralNumber" text,
    "TypeID" integer,
    "TotalArea" numeric,
    "Extension" numeric,
    "Volume" numeric,
    "Floors" integer,
    "GroundFloors" integer,
    "UndergroundFloors" integer,
    "Address" text,
    "EgrnDate" date,
    "EgrnNumber" text,
    "CadastralEngineer" text,
    "CadastralCost" numeric,
    "PurposeID" integer,
    "RoomKind" text,
    "YearBuilt" integer,
    "YearCommissioning" integer,
    "SpecialMarks" text,
    "PermittedUse" text[],
    "CulturalHeritage" text,
    "UnsuitableForLiving" text,
    "ParentID" integer,
    "AscendantID" integer,
    "DescendantID" integer,
    "MarketCost" numeric,
    "Discount" double precision,
    "CollateralValue" numeric,
    "FactUse" text,
    "Contradiction" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_EstateObject" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."EstateObject_Materials" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OwnerID" integer NOT NULL,
    "ObjectID" integer NOT NULL,
    CONSTRAINT "PK_EstateObject_Materials" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."EstateObjectType" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" text,
    "CurrentUserID" integer,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_EstateObjectType" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."FinSource" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" character varying(4),
    "CurrentUserID" integer,
    "Version" timestamp with time zone,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_FinSource" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."FloorCategory" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Status" integer NOT NULL,
    "AuthorID" integer NOT NULL,
    "Code" character varying(4),
    "LowerLimit" integer,
    "UpperLimit" integer,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_FloorCategory" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."FounderEntity" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationID" integer NOT NULL,
    "FounderOrganizationID" integer NOT NULL,
    "Participation" double precision NOT NULL,
    "Note" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_FounderEntity" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."FounderPerson" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationID" integer NOT NULL,
    "PersonID" integer NOT NULL,
    "Participation" double precision NOT NULL,
    "Note" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_FounderPerson" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."LandCategory" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" text,
    "CurrentUserID" integer,
    "Version" timestamp with time zone,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_LandCategory" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."MonthlyData" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ConstructionSiteID" integer,
    "Year" integer,
    "Month" integer,
    "Calculate" boolean NOT NULL,
    "Title" text,
    "Comment" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_MonthlyData" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Organization" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Status" integer NOT NULL,
    "INN" character varying(12),
    "SRO" character varying(255),
    "ClientID" text,
    "RegionID" integer,
    "Address" text,
    "CEO" text,
    "Email" text,
    "Phone" text,
    "WebSite" text,
    "AddInfo" text,
    "GroupID" integer,
    "TownID" integer,
    "Code" character varying(50),
    "CurrentUserID" integer,
    "Version" timestamp with time zone,
    "AdditionalPropertiesConfigID" integer,
    "AdditionalProperties" text,
    "RatingERZ" numeric,
    "NegativeInfo" text,
    "FoundersInfo" text,
    "ActivityInfo" text,
    "SPV" boolean NOT NULL,
    "OGRN" character varying(13),
    "KPP" character varying(9),
    "Category" integer,
    "StabilityCriteria1" double precision,
    "StabilityCriteria2" double precision,
    "StabilityCriteria3" double precision,
    "StabilityCriteria4" double precision,
    "StabilityCriteria5" double precision,
    "StabilityCriteria6" double precision,
    "StabilityCriteria7" double precision,
    "Criteria4Result" boolean NOT NULL,
    "Criteria5Result" boolean NOT NULL,
    "Criteria6Result" boolean NOT NULL,
    "Criteria7Result" boolean NOT NULL,
    "Criteria1Result" boolean NOT NULL,
    "Criteria2Result" boolean NOT NULL,
    "Criteria3Result" boolean NOT NULL,
    "Beneficiaries" text,
    "InsuranceСompanyAccreditation" boolean NOT NULL,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_Organization" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."OrganizationPerson" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationID" integer,
    "FirstName" text,
    "MiddleName" text,
    "LastName" text,
    "OrganizationPosition" text,
    "ContactEmail" text,
    "ContactPhone" text,
    "ContactDescription" text,
    "Status" integer,
    "SourceID" integer,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_OrganizationPerson" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Payment" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Status" integer NOT NULL,
    "Description" text,
    "Sum" numeric,
    "DeclaredSum" numeric,
    "PaymentDate" date NOT NULL,
    "PaymentOrder" text,
    "TypeID" integer,
    "FinSourceID" integer,
    "TrancheNumber" integer NOT NULL,
    "WBSContractID" integer,
    "ContractID" integer,
    "TrancheID" integer,
    "PreviousID" integer,
    "DateUpdate" date,
    "PaymentFile" text,
    "SumClosingDocument" numeric,
    "PaymentKind" integer,
    "ProjectDocID" integer,
    "Version" timestamp with time zone,
    "Color" text,
    "PaymentNumber" text,
    "DuplicateColor" text,
    "Verified" boolean NOT NULL,
    "Hidden" boolean NOT NULL,
    "PlanMonth" integer NOT NULL,
    "PlanQuarter" integer NOT NULL,
    "PlanYear" integer NOT NULL,
    CONSTRAINT "PK_Payment" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."PaymentStatus" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" character varying(4),
    "CurrentUserID" integer,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_PaymentStatus" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."PaymentType" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" character varying(4),
    "CurrentUserID" integer,
    "Version" timestamp with time zone,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_PaymentType" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."ProjectСoncept" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OptimalRoomAreas" boolean NOT NULL,
    "AbsenceLargeRooms" boolean NOT NULL,
    "AbsenceOfIlliquidAreas" boolean NOT NULL,
    "AbsenceExcessCommercialAreas" boolean NOT NULL,
    "Provision" boolean NOT NULL,
    "Other" boolean NOT NULL,
    "Сonclusion" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_ProjectСoncept" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."ProjectAudit" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "ConstructionSiteID" integer,
    "Date" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "Stage" integer NOT NULL,
    "SubmittedDocumentsID" integer,
    "FileProject" text,
    "AuthorID" integer,
    "ResponsibleID" integer,
    "ProjectID" integer,
    "Conclusion" integer,
    "FullFillDate" timestamp with time zone,
    "PlanDate" date,
    "FactDate" timestamp with time zone,
    "IsComplete" boolean NOT NULL,
    "Number" integer,
    "Comment" text,
    "Files" text,
    "PaymentSum" numeric,
    "AgreedSum" numeric,
    "TrancheID" integer,
    "Summary" text,
    "ApprovalDate" date,
    "StartDate" timestamp with time zone,
    "ReportDate" date,
    "CheckListID" integer,
    "Version" timestamp with time zone,
    "InspectionDate" date,
    "InspectionExecutorID" integer,
    "InspectionConclusion" text,
    "InspectionFile" text,
    "UpdateDateTime" timestamp with time zone,
    "ProjectСonceptID" integer,
    "NegativeComment" text,
    "ConceptCompliance" text,
    "IsMkkOutput" boolean NOT NULL,
    "IsTechAudit" boolean NOT NULL,
    "CommentSecond" text,
    "CommentThird" text,
    "EntryLiquidity" text,
    "CadastralAreaLiquidity" text,
    "CadastralAreaInsurance" text,
    "CadastralAreaMonitoring" text,
    "BusinessProcessId" text,
    "ConcordantOneID" integer,
    "ConcordantTwoID" integer,
    "ConcordantThreeID" integer,
    "ConcordantFourID" integer,
    "ConcordantFiveID" integer,
    "AssignmentDate" timestamp with time zone,
    "DispatchDate" timestamp with time zone,
    "CuratorID" integer,
    "ReportFiles" text,
    "ProjectRatesPricesID" integer,
    "IsKIB" boolean,
    "IsForManagementHead" boolean,
    "ClientFullName" text,
    "CompanyGroupName" text,
    "InitiatorFullName" text,
    "IsMoscow" boolean,
    "FileHistory" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_ProjectAudit" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."ProjectDoc" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" character varying(255),
    "ProjectID" integer NOT NULL,
    "ConstructionSiteID" integer,
    "BaseID" integer,
    "DocumentKindID" integer NOT NULL,
    "CategoryID" integer NOT NULL,
    "DocumentNumber" text,
    "DocumentDate" date,
    "ExpirationDate" date,
    "OrganizationID" integer,
    "SortOrder" double precision,
    "Files" text,
    "AdditionalPropertiesConfigID" integer,
    "AdditionalProperties" text,
    "IssuedToID" integer,
    "CheckListID" integer,
    "IsAccepted" boolean NOT NULL,
    "Color" text,
    "Comment" text,
    "NotDeveloped" boolean NOT NULL,
    "ComplianceComment" text,
    "Hidden" boolean NOT NULL,
    "Version" timestamp with time zone,
    CONSTRAINT "PK_ProjectDoc" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."ProjectRatesPrices" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ProjectID" integer,
    "Title" text,
    "AuthorID" integer,
    "Status" integer NOT NULL,
    "ApprovalDate" date,
    "IsMain" boolean NOT NULL,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_ProjectRatesPrices" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Purpose" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" text,
    "CurrentUserID" integer,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Purpose" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."QuarterRatesPrices" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RatesPricesID" integer NOT NULL,
    "Stage" integer,
    "Period" date,
    "Quarter" integer,
    "Year" integer,
    "PrevPeriodID" integer,
    "ModelPeriodNum" integer,
    "ClientResidentialRates" double precision,
    "ClientResidentialCost" numeric,
    "EstimatedResidentialCost" numeric,
    "EstimatedResidentialCostInfl" numeric,
    "ResidentialCostIncrease" double precision,
    "EstimatedResidentialRatesSQ" double precision,
    "EstimatedResidentialRatesPercentage" double precision,
    "ResidentialPeriodTotalCost" numeric,
    "ClientNonresidentialRates" double precision,
    "ClentNonresidentialCost" numeric,
    "EstimatedNonresidentialCost" numeric,
    "NonresidentialCostIncrease" double precision,
    "EstimatedNonresidentialRatesSQ" double precision,
    "EstimatedNonresidentialRatesPercetage" double precision,
    "NonresidentialPeriodTotalCost" numeric,
    "ClientOtherNonresidentialRates" double precision,
    "ClientOtherNonresidentialCost" numeric,
    "EstimatedOtherNonresidentialRatesPercetage" double precision,
    "OtherNonresidentialCostIncrease" double precision,
    "EstimatedOtherNonresidentialRatesSQ" double precision,
    "EstimatedOtherNonresidentialCost" numeric,
    "OtherNonresidentialPeriodTotalCost" numeric,
    "ClientParkingRates" double precision,
    "ClientParkingCost" numeric,
    "EstimatedParkingCost" numeric,
    "ParkingCostIncrease" double precision,
    "EstimatedParkingRatesSQ" double precision,
    "EstimatedParkingRatesPercentage" double precision,
    "ParkingPeriodTotalCost" numeric,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_QuarterRatesPrices" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Queues" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Status" integer NOT NULL,
    "AuthorID" integer,
    "Code" character varying(4),
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_Queues" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Region" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" character varying(4),
    "CurrentUserID" integer,
    "Version" timestamp with time zone,
    "File" text,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Region" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Restriction" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "CadastralAreaID" integer,
    "EstateObjectID" integer,
    "Title" text,
    "Registration" text,
    "TypeID" integer,
    "RegistrationDate" date,
    "StartDate" date,
    "Validity" text,
    "Basis" text,
    "Beneficiary" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_Restriction" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Right" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "CadastralAreaID" integer,
    "EstateObjectID" integer,
    "RestrictionTypeID" integer,
    "Title" text,
    "Registration" text,
    "DateTheRight" date,
    "RegistrationDate" date,
    "RightExpirationDate" date,
    "TerminateDate" date,
    "Basis" text,
    "RightHolder" text,
    "RightCost" numeric,
    "RightShare" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_Right" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."RightRestrictionType" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" text,
    "CurrentUserID" integer,
    "Version" timestamp with time zone,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_RightRestrictionType" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Room" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "SiteID" integer NOT NULL,
    "SectionID" integer,
    "Number" text,
    "Floor" text,
    "KindID" integer NOT NULL,
    "RoomsNumber" integer,
    "IsStudio" boolean NOT NULL,
    "TotalArea" double precision,
    "LivingArea" double precision,
    "Description" text,
    "Cost" numeric,
    "IsSeparateEntrance" text,
    "IsShowcaseWindows" text,
    "TotalAreaWithoutSummerRoom" double precision,
    "SummerRoomArea" double precision,
    "CostForOne" numeric,
    "ExplicationNumber" text,
    "BuildingSection" text,
    "UniqueNumber" text,
    "ProjectArea" double precision NOT NULL,
    "RoomPurpose" text,
    "ParkingPlaceType" text,
    "CadastralNumber" text,
    "IsWithdrawn" boolean NOT NULL,
    "RoomCategory" integer,
    "ActiveShareAgreement" integer,
    "CandidateShareAgreement" integer,
    "ActiveEscrowAccount" integer,
    "CandidateEscrowAccount" integer,
    "CalculatedCostPerM" numeric,
    "MarketCostPerM" numeric,
    "ZalogCostPerM" numeric,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_Room" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."RoomKind" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "ShortTitle" text,
    "Code" character varying(5),
    "RoomCategory" integer,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_RoomKind" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."SectionType" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" character varying(4),
    "CurrentUserID" integer,
    "Version" timestamp with time zone,
    "SortOrder" integer NOT NULL,
    "IsResidential" boolean NOT NULL,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_SectionType" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."ShareAgreement" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Number" text,
    "Date" date,
    "ConstructionPermitNumber" text,
    "ConstructionPermitDate" date,
    "ProjectNumber" text,
    "ProjectTitle" text,
    "DeveloperPIN" text,
    "DeveloperINN" text,
    "StateRegistrationStatus" text,
    "StateRegistrationNumber" text,
    "FilingDate" date,
    "RegistrationDate" date,
    "SerialNumber" text,
    "RoomKind" text,
    "HouseNumber" text,
    "SectionNumber" text,
    "RoomNumber" text,
    "ConditionalNumber" text,
    "TotalArea" double precision,
    "TotalLivingArea" double precision,
    "CadastralNumber" text,
    "Cost" numeric,
    "Deadline" date,
    "DepositedAmount" numeric,
    "IsBorrowedFunds" boolean NOT NULL,
    "IsPreferentialRate" boolean NOT NULL,
    "BudgetFundsAmount" numeric,
    "Street" text,
    "DepositorFullName" text,
    "MotherFundAmount" numeric,
    "IsRegisteredProvided" boolean NOT NULL,
    "HouseNumberPermit" text,
    "SiteID" integer,
    "ProjectID" integer,
    "StageNumber" text,
    "RoomID" integer,
    "ValidityStatus" integer,
    "RoomKindRefID" integer,
    "MonthlyDataID" integer,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_ShareAgreement" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."SignOfTrouble" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Type" text,
    "Description" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_SignOfTrouble" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."SiteRatesPrices" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "SiteID" integer NOT NULL,
    "Title" text,
    "ProjectID" integer,
    "AnalysisDate" date,
    "CommissioningPeriod" date,
    "AuthorID" integer,
    "EstimatedResidentialCostStart" numeric,
    "EstimatedResidentialCostCommissioning" numeric,
    "EstimatedResidentialCostFinish" numeric,
    "Indexing" double precision,
    "EstimatedNonResidentialCost" numeric,
    "EstimatedOtherNonresidentialCost" numeric,
    "EstimatedParkingCost" numeric,
    "ClientResidentialCostStart" numeric,
    "ClientResidentialCostCommissioning" numeric,
    "ClientResidentialCostFinish" numeric,
    "ClientOtherNonresidentialCost" numeric,
    "ClientNonResidentialCost" numeric,
    "ClientParkingCost" numeric,
    "CompetitorResidentialCostStart" numeric,
    "CompetitorResidentialCostCommissioning" numeric,
    "CompetitorNonResidentialCost" numeric,
    "CompetitorOtherNonresidentialCost" numeric,
    "CompetitorParkingCost" numeric,
    "QuartersCount" integer,
    "DiscountQuaters" integer,
    "DiscountLastRate" double precision,
    "IsMain" boolean NOT NULL,
    "IsChanged" boolean NOT NULL,
    "FirstQuarterRate" double precision,
    "IsInfaltionCalculation" boolean NOT NULL,
    "ProjectAuditID" integer,
    "CommissioningRate" double precision,
    "IsClientDates" boolean NOT NULL,
    "DocDate" date,
    "FirstQuarterRateNonRes" double precision,
    "FirstQuarterRateOtherNonRes" double precision,
    "FirstQuarterRateParking" double precision,
    "Status" integer,
    "ApprovalDate" date,
    "SiteAnalogID" integer,
    "CompetitorRezPriceStartID" integer,
    "CompetitorRezPriceComisID" integer,
    "CompetitorNonRezPriceID" integer,
    "CompetitorOtherNonRezPriceID" integer,
    "CompetitorParkingPriceID" integer,
    "Comments" text,
    "IsRoomModel" boolean NOT NULL,
    "AreaComment" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_SiteRatesPrices" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."SubmittedDocuments" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "ProjectID" integer NOT NULL,
    "OrganizationID" integer,
    "Status" integer NOT NULL,
    "DocumentCount" integer,
    "DocumentAgreeCount" integer,
    "InWork" integer NOT NULL,
    "Color" text,
    "SubmittedDocStage" integer NOT NULL,
    "ResponsibleID" integer,
    "PersonID" integer,
    "AuthorID" integer,
    "Created" timestamp with time zone,
    "Message" text,
    "ConstructionSiteID" integer,
    "Hidden" boolean NOT NULL,
    "Version" timestamp with time zone,
    CONSTRAINT "PK_SubmittedDocuments" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."SubmittedDocumentsItem" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "SubmittedDocumentsID" integer,
    "DocumentKindID" integer,
    "DocumentNumber" character varying(255),
    "DocumentDate" date,
    "Property" integer NOT NULL,
    "Status" integer NOT NULL,
    "Files" text,
    "SortOrder" double precision NOT NULL,
    "OrganizationID" integer,
    "ExpirationDate" date,
    "IsFileAttached" boolean NOT NULL,
    "ConstructionSiteID" integer,
    "ConstructionProjectID" integer,
    "Client" text,
    "Hidden" boolean NOT NULL,
    "Version" timestamp with time zone,
    CONSTRAINT "PK_SubmittedDocumentsItem" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Town" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RegionID" integer NOT NULL,
    "TypeID" integer,
    "Code" character varying(4),
    "CurrentUserID" integer,
    "Version" timestamp with time zone,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Town" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."TownType" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Status" integer NOT NULL,
    "Version" timestamp with time zone,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_TownType" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Tranche" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Date" date,
    "Number" integer,
    "Title" character varying(255),
    "ProjectID" integer,
    "ResponsibleID" integer,
    "Status" integer NOT NULL,
    "Comment" text,
    "Files" text,
    "ProjectDocID" integer,
    "ConstructionSiteID" integer,
    "IdentifierKK" text,
    "IdentifierZPLM" character varying(255),
    "Hidden" boolean NOT NULL,
    "Version" timestamp with time zone,
    CONSTRAINT "PK_Tranche" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."Unit" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" character varying(4),
    "CurrentUserID" integer,
    "Version" timestamp with time zone,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Unit" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."UseTypeArea" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" text,
    "CurrentUserID" integer,
    "Version" timestamp with time zone,
    "Hidden" boolean NOT NULL,
    "Title" character varying(255),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_UseTypeArea" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."WBS" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" text,
    "Code" character varying(255),
    "FZItem" character varying(255),
    "ProjectID" integer,
    "DeclaredSum" numeric,
    "ConfirmedSum" numeric,
    "UnitID" integer,
    "Volume" numeric NOT NULL,
    "WorkPlanPeriod_Start" timestamp with time zone,
    "WorkPlanPeriod_End" timestamp with time zone,
    "WorkPlanEstimatedEnd" date,
    "PaymentPlanSum" numeric,
    "PaymentPlanPeriod_Start" timestamp with time zone,
    "PaymentPlanPeriod_End" timestamp with time zone,
    "AnalogPercentage" text,
    "TreeLevel" integer NOT NULL,
    "ConstructionSiteID" integer,
    "SumContracts" numeric NOT NULL,
    "SumAcceptedContract" numeric NOT NULL,
    "SumPerformerDone" numeric NOT NULL,
    "SumPayment" numeric NOT NULL,
    "Version" timestamp with time zone,
    "PerformerDonePercent" integer NOT NULL,
    "Comment" text,
    "Note" text,
    "ActuallyInvested" numeric,
    "Hidden" boolean NOT NULL,
    "SysAllParents" text,
    "SortOrder" double precision NOT NULL,
    "ParentID" integer,
    CONSTRAINT "PK_WBS" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."WBSContract" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "WBSID" integer,
    "ContractID" integer,
    "ProjectID" integer,
    "ContractSum" numeric,
    "ConstructionSiteID" integer,
    "Version" timestamp with time zone,
    "ContractFinalSum" numeric,
    "PaymentSum" numeric,
    "AcceptedSum" numeric,
    "Color" text,
    "Hidden" boolean NOT NULL,
    CONSTRAINT "PK_WBSContract" PRIMARY KEY ("ID")
);

-- ═══════════════════════ Foreign keys ═══════════════════════

ALTER TABLE "Data"."AcceptedContract" ADD CONSTRAINT "FK_AcceptedContract_WBSContract_WBSContractID" FOREIGN KEY ("WBSContractID") REFERENCES "Data"."WBSContract" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."AcceptedContract" ADD CONSTRAINT "FK_AcceptedContract_ClosureDocument_ClosureDocumentID" FOREIGN KEY ("ClosureDocumentID") REFERENCES "Data"."ClosureDocument" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."AcceptedContract" ADD CONSTRAINT "FK_AcceptedContract_Contract_ContractID" FOREIGN KEY ("ContractID") REFERENCES "Data"."Contract" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."AcceptedContract" ADD CONSTRAINT "FK_AcceptedContract_Unit_UnitID" FOREIGN KEY ("UnitID") REFERENCES "Data"."Unit" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."AcceptedContract" ADD CONSTRAINT "FK_AcceptedContract_Payment_PaymentID" FOREIGN KEY ("PaymentID") REFERENCES "Data"."Payment" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."AddAgreement" ADD CONSTRAINT "FK_AddAgreement_Contract_ContractID" FOREIGN KEY ("ContractID") REFERENCES "Data"."Contract" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."AddAgreement" ADD CONSTRAINT "FK_AddAgreement_ProjectDoc_ProjectDocID" FOREIGN KEY ("ProjectDocID") REFERENCES "Data"."ProjectDoc" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Analysis" ADD CONSTRAINT "FK_Analysis_ProjectAudit_AuditID" FOREIGN KEY ("AuditID") REFERENCES "Data"."ProjectAudit" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Analysis" ADD CONSTRAINT "FK_Analysis_User_AuthorID" FOREIGN KEY ("AuthorID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Analysis" ADD CONSTRAINT "FK_Analysis_User_ResponsibleID" FOREIGN KEY ("ResponsibleID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."AreaDocument" ADD CONSTRAINT "FK_AreaDocument_ProjectDoc_ID" FOREIGN KEY ("ID") REFERENCES "Data"."ProjectDoc" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."AreaDocument" ADD CONSTRAINT "FK_AreaDocument_ProjectDoc_ProjectDocID" FOREIGN KEY ("ProjectDocID") REFERENCES "Data"."ProjectDoc" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."AreaDocument" ADD CONSTRAINT "FK_AreaDocument_Analysis_AnalysisID" FOREIGN KEY ("AnalysisID") REFERENCES "Data"."Analysis" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."AreaDocument" ADD CONSTRAINT "FK_AreaDocument_UseTypeArea_UseTypeConditionalID" FOREIGN KEY ("UseTypeConditionalID") REFERENCES "Data"."UseTypeArea" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."BuildingMaterial" ADD CONSTRAINT "FK_BuildingMaterial_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."CadastralArea" ADD CONSTRAINT "FK_CadastralArea_LandCategory_LandCategoryID" FOREIGN KEY ("LandCategoryID") REFERENCES "Data"."LandCategory" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."CadastralArea" ADD CONSTRAINT "FK_CadastralArea_RightRestrictionType_InitRightRestrictionType" FOREIGN KEY ("InitRightRestrictionTypeID") REFERENCES "Data"."RightRestrictionType" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."CadastralArea" ADD CONSTRAINT "FK_CadastralArea_UseTypeArea_FactUseTypeAreaID" FOREIGN KEY ("FactUseTypeAreaID") REFERENCES "Data"."UseTypeArea" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."CadastralArea" ADD CONSTRAINT "FK_CadastralArea_CadastralArea_ParentID" FOREIGN KEY ("ParentID") REFERENCES "Data"."CadastralArea" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."CadastralArea" ADD CONSTRAINT "FK_CadastralArea_AreaDocument_AreaDocumentID" FOREIGN KEY ("AreaDocumentID") REFERENCES "Data"."AreaDocument" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Chapter" ADD CONSTRAINT "FK_Chapter_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Chapter" ADD CONSTRAINT "FK_Chapter_Chapter_ParentID" FOREIGN KEY ("ParentID") REFERENCES "Data"."Chapter" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."CheckList" ADD CONSTRAINT "FK_CheckList_SubmittedDocuments_SubmittedDocumentsID" FOREIGN KEY ("SubmittedDocumentsID") REFERENCES "Data"."SubmittedDocuments" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."CheckList" ADD CONSTRAINT "FK_CheckList_User_ResponsibleID" FOREIGN KEY ("ResponsibleID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ClientData" ADD CONSTRAINT "FK_ClientData_QuarterRatesPrices_QuarterRatesPricesID" FOREIGN KEY ("QuarterRatesPricesID") REFERENCES "Data"."QuarterRatesPrices" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ClientData" ADD CONSTRAINT "FK_ClientData_SiteRatesPrices_SiteRatesPricesID" FOREIGN KEY ("SiteRatesPricesID") REFERENCES "Data"."SiteRatesPrices" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ClientSegment" ADD CONSTRAINT "FK_ClientSegment_User_ModifiedByID" FOREIGN KEY ("ModifiedByID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ClosureDocument" ADD CONSTRAINT "FK_ClosureDocument_Contract_ContractID" FOREIGN KEY ("ContractID") REFERENCES "Data"."Contract" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ClosureDocument" ADD CONSTRAINT "FK_ClosureDocument_ProjectDoc_ProjectDocID" FOREIGN KEY ("ProjectDocID") REFERENCES "Data"."ProjectDoc" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ConstructionSection" ADD CONSTRAINT "FK_ConstructionSection_SectionType_TypeID" FOREIGN KEY ("TypeID") REFERENCES "Data"."SectionType" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ConstructionSection" ADD CONSTRAINT "FK_ConstructionSection_BuildingMaterial_BuildingMaterialID" FOREIGN KEY ("BuildingMaterialID") REFERENCES "Data"."BuildingMaterial" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ConstructionSite_Queues" ADD CONSTRAINT "FK_ConstructionSite_Queues_Queues_ObjectID" FOREIGN KEY ("ObjectID") REFERENCES "Data"."Queues" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ConstructionType" ADD CONSTRAINT "FK_ConstructionType_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Contract" ADD CONSTRAINT "FK_Contract_Contract_PreviousID" FOREIGN KEY ("PreviousID") REFERENCES "Data"."Contract" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Contract" ADD CONSTRAINT "FK_Contract_ContractCurrency_ContractCurrencyID" FOREIGN KEY ("ContractCurrencyID") REFERENCES "Data"."ContractCurrency" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Contract" ADD CONSTRAINT "FK_Contract_ProjectDoc_ProjectDocID" FOREIGN KEY ("ProjectDocID") REFERENCES "Data"."ProjectDoc" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ContractCurrency" ADD CONSTRAINT "FK_ContractCurrency_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."DocSubType" ADD CONSTRAINT "FK_DocSubType_Chapter_ChapterID" FOREIGN KEY ("ChapterID") REFERENCES "Data"."Chapter" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."DocSubType" ADD CONSTRAINT "FK_DocSubType_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."DocSubType" ADD CONSTRAINT "FK_DocSubType_User_AuthorID" FOREIGN KEY ("AuthorID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."DocSubType" ADD CONSTRAINT "FK_DocSubType_DocSubType_ParentID" FOREIGN KEY ("ParentID") REFERENCES "Data"."DocSubType" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EscrowAccount" ADD CONSTRAINT "FK_EscrowAccount_SignOfTrouble_SignOfTroubleID" FOREIGN KEY ("SignOfTroubleID") REFERENCES "Data"."SignOfTrouble" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EscrowAccount" ADD CONSTRAINT "FK_EscrowAccount_EscrowAccountStatus_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Data"."EscrowAccountStatus" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EscrowAccount" ADD CONSTRAINT "FK_EscrowAccount_ContractCurrency_ContractCurrencyID" FOREIGN KEY ("ContractCurrencyID") REFERENCES "Data"."ContractCurrency" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EscrowAccount" ADD CONSTRAINT "FK_EscrowAccount_Room_RoomID" FOREIGN KEY ("RoomID") REFERENCES "Data"."Room" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EscrowAccount" ADD CONSTRAINT "FK_EscrowAccount_RoomKind_RoomKindRefID" FOREIGN KEY ("RoomKindRefID") REFERENCES "Data"."RoomKind" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EscrowAccount_SlaveObject" ADD CONSTRAINT "FK_EscrowAccount_SlaveObject_EscrowAccount_OwnerID" FOREIGN KEY ("OwnerID") REFERENCES "Data"."EscrowAccount" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EstateClass" ADD CONSTRAINT "FK_EstateClass_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EstateObject" ADD CONSTRAINT "FK_EstateObject_EstateObjectType_TypeID" FOREIGN KEY ("TypeID") REFERENCES "Data"."EstateObjectType" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EstateObject" ADD CONSTRAINT "FK_EstateObject_Purpose_PurposeID" FOREIGN KEY ("PurposeID") REFERENCES "Data"."Purpose" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EstateObject" ADD CONSTRAINT "FK_EstateObject_EstateObject_ParentID" FOREIGN KEY ("ParentID") REFERENCES "Data"."EstateObject" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EstateObject" ADD CONSTRAINT "FK_EstateObject_EstateObject_AscendantID" FOREIGN KEY ("AscendantID") REFERENCES "Data"."EstateObject" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EstateObject" ADD CONSTRAINT "FK_EstateObject_EstateObject_DescendantID" FOREIGN KEY ("DescendantID") REFERENCES "Data"."EstateObject" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EstateObject_Materials" ADD CONSTRAINT "FK_EstateObject_Materials_EstateObject_OwnerID" FOREIGN KEY ("OwnerID") REFERENCES "Data"."EstateObject" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EstateObject_Materials" ADD CONSTRAINT "FK_EstateObject_Materials_BuildingMaterial_ObjectID" FOREIGN KEY ("ObjectID") REFERENCES "Data"."BuildingMaterial" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."EstateObjectType" ADD CONSTRAINT "FK_EstateObjectType_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."FinSource" ADD CONSTRAINT "FK_FinSource_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."FloorCategory" ADD CONSTRAINT "FK_FloorCategory_User_AuthorID" FOREIGN KEY ("AuthorID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."FounderEntity" ADD CONSTRAINT "FK_FounderEntity_Organization_OrganizationID" FOREIGN KEY ("OrganizationID") REFERENCES "Data"."Organization" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."FounderEntity" ADD CONSTRAINT "FK_FounderEntity_Organization_FounderOrganizationID" FOREIGN KEY ("FounderOrganizationID") REFERENCES "Data"."Organization" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."FounderPerson" ADD CONSTRAINT "FK_FounderPerson_Organization_OrganizationID" FOREIGN KEY ("OrganizationID") REFERENCES "Data"."Organization" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."FounderPerson" ADD CONSTRAINT "FK_FounderPerson_OrganizationPerson_PersonID" FOREIGN KEY ("PersonID") REFERENCES "Data"."OrganizationPerson" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."LandCategory" ADD CONSTRAINT "FK_LandCategory_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Organization" ADD CONSTRAINT "FK_Organization_Region_RegionID" FOREIGN KEY ("RegionID") REFERENCES "Data"."Region" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Organization" ADD CONSTRAINT "FK_Organization_CompanyGroup_GroupID" FOREIGN KEY ("GroupID") REFERENCES "Data"."CompanyGroup" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Organization" ADD CONSTRAINT "FK_Organization_Town_TownID" FOREIGN KEY ("TownID") REFERENCES "Data"."Town" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Organization" ADD CONSTRAINT "FK_Organization_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Organization" ADD CONSTRAINT "FK_Organization_AdditionalPropertiesConfig_AdditionalPropertie" FOREIGN KEY ("AdditionalPropertiesConfigID") REFERENCES "Data"."AdditionalPropertiesConfig" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."OrganizationPerson" ADD CONSTRAINT "FK_OrganizationPerson_Organization_OrganizationID" FOREIGN KEY ("OrganizationID") REFERENCES "Data"."Organization" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Payment" ADD CONSTRAINT "FK_Payment_PaymentType_TypeID" FOREIGN KEY ("TypeID") REFERENCES "Data"."PaymentType" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Payment" ADD CONSTRAINT "FK_Payment_FinSource_FinSourceID" FOREIGN KEY ("FinSourceID") REFERENCES "Data"."FinSource" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Payment" ADD CONSTRAINT "FK_Payment_WBSContract_WBSContractID" FOREIGN KEY ("WBSContractID") REFERENCES "Data"."WBSContract" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Payment" ADD CONSTRAINT "FK_Payment_Contract_ContractID" FOREIGN KEY ("ContractID") REFERENCES "Data"."Contract" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Payment" ADD CONSTRAINT "FK_Payment_Tranche_TrancheID" FOREIGN KEY ("TrancheID") REFERENCES "Data"."Tranche" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Payment" ADD CONSTRAINT "FK_Payment_Payment_PreviousID" FOREIGN KEY ("PreviousID") REFERENCES "Data"."Payment" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Payment" ADD CONSTRAINT "FK_Payment_ProjectDoc_ProjectDocID" FOREIGN KEY ("ProjectDocID") REFERENCES "Data"."ProjectDoc" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."PaymentStatus" ADD CONSTRAINT "FK_PaymentStatus_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."PaymentType" ADD CONSTRAINT "FK_PaymentType_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_SubmittedDocuments_SubmittedDocumentsID" FOREIGN KEY ("SubmittedDocumentsID") REFERENCES "Data"."SubmittedDocuments" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_User_AuthorID" FOREIGN KEY ("AuthorID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_User_ResponsibleID" FOREIGN KEY ("ResponsibleID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_Tranche_TrancheID" FOREIGN KEY ("TrancheID") REFERENCES "Data"."Tranche" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_CheckList_CheckListID" FOREIGN KEY ("CheckListID") REFERENCES "Data"."CheckList" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_User_InspectionExecutorID" FOREIGN KEY ("InspectionExecutorID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_ProjectСoncept_ProjectСonceptID" FOREIGN KEY ("ProjectСonceptID") REFERENCES "Data"."ProjectСoncept" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_User_ConcordantOneID" FOREIGN KEY ("ConcordantOneID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_User_ConcordantTwoID" FOREIGN KEY ("ConcordantTwoID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_User_ConcordantThreeID" FOREIGN KEY ("ConcordantThreeID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_User_ConcordantFourID" FOREIGN KEY ("ConcordantFourID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_User_ConcordantFiveID" FOREIGN KEY ("ConcordantFiveID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_User_CuratorID" FOREIGN KEY ("CuratorID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectAudit" ADD CONSTRAINT "FK_ProjectAudit_ProjectRatesPrices_ProjectRatesPricesID" FOREIGN KEY ("ProjectRatesPricesID") REFERENCES "Data"."ProjectRatesPrices" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectDoc" ADD CONSTRAINT "FK_ProjectDoc_SubmittedDocumentsItem_BaseID" FOREIGN KEY ("BaseID") REFERENCES "Data"."SubmittedDocumentsItem" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectDoc" ADD CONSTRAINT "FK_ProjectDoc_DocSubType_DocumentKindID" FOREIGN KEY ("DocumentKindID") REFERENCES "Data"."DocSubType" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectDoc" ADD CONSTRAINT "FK_ProjectDoc_DocSubType_CategoryID" FOREIGN KEY ("CategoryID") REFERENCES "Data"."DocSubType" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectDoc" ADD CONSTRAINT "FK_ProjectDoc_Organization_OrganizationID" FOREIGN KEY ("OrganizationID") REFERENCES "Data"."Organization" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectDoc" ADD CONSTRAINT "FK_ProjectDoc_AdditionalPropertiesConfig_AdditionalPropertiesC" FOREIGN KEY ("AdditionalPropertiesConfigID") REFERENCES "Data"."AdditionalPropertiesConfig" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectDoc" ADD CONSTRAINT "FK_ProjectDoc_Organization_IssuedToID" FOREIGN KEY ("IssuedToID") REFERENCES "Data"."Organization" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectDoc" ADD CONSTRAINT "FK_ProjectDoc_CheckList_CheckListID" FOREIGN KEY ("CheckListID") REFERENCES "Data"."CheckList" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ProjectRatesPrices" ADD CONSTRAINT "FK_ProjectRatesPrices_User_AuthorID" FOREIGN KEY ("AuthorID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Purpose" ADD CONSTRAINT "FK_Purpose_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."QuarterRatesPrices" ADD CONSTRAINT "FK_QuarterRatesPrices_SiteRatesPrices_RatesPricesID" FOREIGN KEY ("RatesPricesID") REFERENCES "Data"."SiteRatesPrices" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."QuarterRatesPrices" ADD CONSTRAINT "FK_QuarterRatesPrices_QuarterRatesPrices_PrevPeriodID" FOREIGN KEY ("PrevPeriodID") REFERENCES "Data"."QuarterRatesPrices" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Queues" ADD CONSTRAINT "FK_Queues_User_AuthorID" FOREIGN KEY ("AuthorID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Region" ADD CONSTRAINT "FK_Region_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Restriction" ADD CONSTRAINT "FK_Restriction_CadastralArea_CadastralAreaID" FOREIGN KEY ("CadastralAreaID") REFERENCES "Data"."CadastralArea" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Restriction" ADD CONSTRAINT "FK_Restriction_EstateObject_EstateObjectID" FOREIGN KEY ("EstateObjectID") REFERENCES "Data"."EstateObject" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Restriction" ADD CONSTRAINT "FK_Restriction_RightRestrictionType_TypeID" FOREIGN KEY ("TypeID") REFERENCES "Data"."RightRestrictionType" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Right" ADD CONSTRAINT "FK_Right_CadastralArea_CadastralAreaID" FOREIGN KEY ("CadastralAreaID") REFERENCES "Data"."CadastralArea" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Right" ADD CONSTRAINT "FK_Right_EstateObject_EstateObjectID" FOREIGN KEY ("EstateObjectID") REFERENCES "Data"."EstateObject" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Right" ADD CONSTRAINT "FK_Right_RightRestrictionType_RestrictionTypeID" FOREIGN KEY ("RestrictionTypeID") REFERENCES "Data"."RightRestrictionType" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."RightRestrictionType" ADD CONSTRAINT "FK_RightRestrictionType_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Room" ADD CONSTRAINT "FK_Room_ConstructionSection_SectionID" FOREIGN KEY ("SectionID") REFERENCES "Data"."ConstructionSection" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Room" ADD CONSTRAINT "FK_Room_RoomKind_KindID" FOREIGN KEY ("KindID") REFERENCES "Data"."RoomKind" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SectionType" ADD CONSTRAINT "FK_SectionType_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ShareAgreement" ADD CONSTRAINT "FK_ShareAgreement_Room_RoomID" FOREIGN KEY ("RoomID") REFERENCES "Data"."Room" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ShareAgreement" ADD CONSTRAINT "FK_ShareAgreement_RoomKind_RoomKindRefID" FOREIGN KEY ("RoomKindRefID") REFERENCES "Data"."RoomKind" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."ShareAgreement" ADD CONSTRAINT "FK_ShareAgreement_MonthlyData_MonthlyDataID" FOREIGN KEY ("MonthlyDataID") REFERENCES "Data"."MonthlyData" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SiteRatesPrices" ADD CONSTRAINT "FK_SiteRatesPrices_User_AuthorID" FOREIGN KEY ("AuthorID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SiteRatesPrices" ADD CONSTRAINT "FK_SiteRatesPrices_ProjectAudit_ProjectAuditID" FOREIGN KEY ("ProjectAuditID") REFERENCES "Data"."ProjectAudit" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SiteRatesPrices" ADD CONSTRAINT "FK_SiteRatesPrices_AnalogCriteria_SiteAnalogID" FOREIGN KEY ("SiteAnalogID") REFERENCES "Data"."AnalogCriteria" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SiteRatesPrices" ADD CONSTRAINT "FK_SiteRatesPrices_AnalogCriteria_CompetitorRezPriceStartID" FOREIGN KEY ("CompetitorRezPriceStartID") REFERENCES "Data"."AnalogCriteria" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SiteRatesPrices" ADD CONSTRAINT "FK_SiteRatesPrices_AnalogCriteria_CompetitorRezPriceComisID" FOREIGN KEY ("CompetitorRezPriceComisID") REFERENCES "Data"."AnalogCriteria" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SiteRatesPrices" ADD CONSTRAINT "FK_SiteRatesPrices_AnalogCriteria_CompetitorNonRezPriceID" FOREIGN KEY ("CompetitorNonRezPriceID") REFERENCES "Data"."AnalogCriteria" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SiteRatesPrices" ADD CONSTRAINT "FK_SiteRatesPrices_AnalogCriteria_CompetitorOtherNonRezPriceID" FOREIGN KEY ("CompetitorOtherNonRezPriceID") REFERENCES "Data"."AnalogCriteria" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SiteRatesPrices" ADD CONSTRAINT "FK_SiteRatesPrices_AnalogCriteria_CompetitorParkingPriceID" FOREIGN KEY ("CompetitorParkingPriceID") REFERENCES "Data"."AnalogCriteria" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SubmittedDocuments" ADD CONSTRAINT "FK_SubmittedDocuments_Organization_OrganizationID" FOREIGN KEY ("OrganizationID") REFERENCES "Data"."Organization" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SubmittedDocuments" ADD CONSTRAINT "FK_SubmittedDocuments_User_ResponsibleID" FOREIGN KEY ("ResponsibleID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SubmittedDocuments" ADD CONSTRAINT "FK_SubmittedDocuments_OrganizationPerson_PersonID" FOREIGN KEY ("PersonID") REFERENCES "Data"."OrganizationPerson" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SubmittedDocuments" ADD CONSTRAINT "FK_SubmittedDocuments_User_AuthorID" FOREIGN KEY ("AuthorID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SubmittedDocumentsItem" ADD CONSTRAINT "FK_SubmittedDocumentsItem_SubmittedDocuments_SubmittedDocument" FOREIGN KEY ("SubmittedDocumentsID") REFERENCES "Data"."SubmittedDocuments" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SubmittedDocumentsItem" ADD CONSTRAINT "FK_SubmittedDocumentsItem_DocSubType_DocumentKindID" FOREIGN KEY ("DocumentKindID") REFERENCES "Data"."DocSubType" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."SubmittedDocumentsItem" ADD CONSTRAINT "FK_SubmittedDocumentsItem_Organization_OrganizationID" FOREIGN KEY ("OrganizationID") REFERENCES "Data"."Organization" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Town" ADD CONSTRAINT "FK_Town_Region_RegionID" FOREIGN KEY ("RegionID") REFERENCES "Data"."Region" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Town" ADD CONSTRAINT "FK_Town_TownType_TypeID" FOREIGN KEY ("TypeID") REFERENCES "Data"."TownType" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Town" ADD CONSTRAINT "FK_Town_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Tranche" ADD CONSTRAINT "FK_Tranche_User_ResponsibleID" FOREIGN KEY ("ResponsibleID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Tranche" ADD CONSTRAINT "FK_Tranche_ProjectDoc_ProjectDocID" FOREIGN KEY ("ProjectDocID") REFERENCES "Data"."ProjectDoc" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."Unit" ADD CONSTRAINT "FK_Unit_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."UseTypeArea" ADD CONSTRAINT "FK_UseTypeArea_User_CurrentUserID" FOREIGN KEY ("CurrentUserID") REFERENCES "Base"."User" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."WBS" ADD CONSTRAINT "FK_WBS_Unit_UnitID" FOREIGN KEY ("UnitID") REFERENCES "Data"."Unit" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."WBS" ADD CONSTRAINT "FK_WBS_WBS_ParentID" FOREIGN KEY ("ParentID") REFERENCES "Data"."WBS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."WBSContract" ADD CONSTRAINT "FK_WBSContract_WBS_WBSID" FOREIGN KEY ("WBSID") REFERENCES "Data"."WBS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Data"."WBSContract" ADD CONSTRAINT "FK_WBSContract_Contract_ContractID" FOREIGN KEY ("ContractID") REFERENCES "Data"."Contract" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
