-- ═══════════════════════════════════════════════════════════════════
-- Дополнительные таблицы, отсутствующие в Context/schema_export.csv
-- ═══════════════════════════════════════════════════════════════════
-- В оригинальном CSV-экспорте отсутствуют корневые таблицы
-- Data.ConstructionProject и Data.ConstructionSite, но на них ссылаются
-- сотни других таблиц через колонки ProjectID / ConstructionSiteID.
--
-- Минимальные определения соответствуют полям, которые возвращает
-- Visary ListView API (см. KiloImportService.Web/src/types/listView.ts).
-- При появлении полного экспорта эти определения нужно заменить.
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS "Data"."ConstructionProject" (
    "ID"              integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title"           character varying(500),
    "IdentifierKK"    character varying(50),
    "IdentifierZPLM"  character varying(50),
    "Type"            text,
    "Phase"           text,
    "RegionID"        integer,
    "TownID"          integer,
    "DeveloperID"     integer,
    "ProjectManagementID" integer,
    "SponsorID"       integer,
    "ProjectPeriod_Start" date,
    "ProjectPeriod_End"   date,
    "Hidden"          boolean NOT NULL DEFAULT false,
    "Version"         timestamp with time zone,
    CONSTRAINT "PK_ConstructionProject" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "Data"."ConstructionSite" (
    "ID"                            integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title"                         character varying(500),
    "ConstructionProjectID"         integer,
    "ConstructionPermissionNumber"  character varying(100),
    "ConstructionProjectNumber"     character varying(100),
    "StageNumber"                   character varying(50),
    "RegionID"                      integer,
    "TownID"                        integer,
    "Address"                       text,
    "Hidden"                        boolean NOT NULL DEFAULT false,
    "Version"                       timestamp with time zone,
    CONSTRAINT "PK_ConstructionSite" PRIMARY KEY ("ID")
);

-- FK на корневые таблицы
ALTER TABLE "Data"."ConstructionSite"
    ADD CONSTRAINT "FK_ConstructionSite_ConstructionProject_ConstructionProjectID"
    FOREIGN KEY ("ConstructionProjectID") REFERENCES "Data"."ConstructionProject" ("ID")
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ═══════════════════════════════════════════════════════════════════
-- Восстановление FK на ConstructionProject / ConstructionSite
-- ═══════════════════════════════════════════════════════════════════
-- Эти 30 колонок-ссылок (ProjectID / SiteID / ConstructionSiteID /
-- ConstructionProjectID) присутствуют в CSV, но FK для них не были
-- созданы автоматически, поскольку target-таблицы отсутствовали.
-- Воссоздаём вручную после создания корневых таблиц.

ALTER TABLE "Data"."AnalogCriteria"        ADD CONSTRAINT "FK_AnalogCriteria_ConstructionSite_ConstructionSiteID"             FOREIGN KEY ("ConstructionSiteID")     REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."Analysis"              ADD CONSTRAINT "FK_Analysis_ConstructionProject_ProjectID"                         FOREIGN KEY ("ProjectID")              REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."CheckList"             ADD CONSTRAINT "FK_CheckList_ConstructionProject_ProjectID"                        FOREIGN KEY ("ProjectID")              REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."CheckList"             ADD CONSTRAINT "FK_CheckList_ConstructionSite_SiteID"                              FOREIGN KEY ("SiteID")                 REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."ClientData"            ADD CONSTRAINT "FK_ClientData_ConstructionSite_SiteID"                             FOREIGN KEY ("SiteID")                 REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."ConstructionSection"   ADD CONSTRAINT "FK_ConstructionSection_ConstructionSite_ConstructionSiteID"        FOREIGN KEY ("ConstructionSiteID")     REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."Contract"              ADD CONSTRAINT "FK_Contract_ConstructionProject_ProjectID"                         FOREIGN KEY ("ProjectID")              REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."EscrowAccount"         ADD CONSTRAINT "FK_EscrowAccount_ConstructionSite_SiteID"                          FOREIGN KEY ("SiteID")                 REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."EscrowAccount"         ADD CONSTRAINT "FK_EscrowAccount_ConstructionProject_ProjectID"                    FOREIGN KEY ("ProjectID")              REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."MonthlyData"           ADD CONSTRAINT "FK_MonthlyData_ConstructionSite_ConstructionSiteID"                FOREIGN KEY ("ConstructionSiteID")     REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."ProjectAudit"          ADD CONSTRAINT "FK_ProjectAudit_ConstructionSite_ConstructionSiteID"               FOREIGN KEY ("ConstructionSiteID")     REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."ProjectAudit"          ADD CONSTRAINT "FK_ProjectAudit_ConstructionProject_ProjectID"                     FOREIGN KEY ("ProjectID")              REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."ProjectDoc"            ADD CONSTRAINT "FK_ProjectDoc_ConstructionProject_ProjectID"                       FOREIGN KEY ("ProjectID")              REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."ProjectDoc"            ADD CONSTRAINT "FK_ProjectDoc_ConstructionSite_ConstructionSiteID"                 FOREIGN KEY ("ConstructionSiteID")     REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."ProjectRatesPrices"    ADD CONSTRAINT "FK_ProjectRatesPrices_ConstructionProject_ProjectID"               FOREIGN KEY ("ProjectID")              REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."Room"                  ADD CONSTRAINT "FK_Room_ConstructionSite_SiteID"                                   FOREIGN KEY ("SiteID")                 REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."ShareAgreement"        ADD CONSTRAINT "FK_ShareAgreement_ConstructionSite_SiteID"                         FOREIGN KEY ("SiteID")                 REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."ShareAgreement"        ADD CONSTRAINT "FK_ShareAgreement_ConstructionProject_ProjectID"                   FOREIGN KEY ("ProjectID")              REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."SiteRatesPrices"       ADD CONSTRAINT "FK_SiteRatesPrices_ConstructionSite_SiteID"                        FOREIGN KEY ("SiteID")                 REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."SiteRatesPrices"       ADD CONSTRAINT "FK_SiteRatesPrices_ConstructionProject_ProjectID"                  FOREIGN KEY ("ProjectID")              REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."SubmittedDocuments"    ADD CONSTRAINT "FK_SubmittedDocuments_ConstructionProject_ProjectID"               FOREIGN KEY ("ProjectID")              REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."SubmittedDocuments"    ADD CONSTRAINT "FK_SubmittedDocuments_ConstructionSite_ConstructionSiteID"         FOREIGN KEY ("ConstructionSiteID")     REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."SubmittedDocumentsItem" ADD CONSTRAINT "FK_SubmittedDocumentsItem_ConstructionSite_ConstructionSiteID"    FOREIGN KEY ("ConstructionSiteID")     REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."SubmittedDocumentsItem" ADD CONSTRAINT "FK_SubmittedDocumentsItem_ConstructionProject_ConstructionProjectID" FOREIGN KEY ("ConstructionProjectID") REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."Tranche"               ADD CONSTRAINT "FK_Tranche_ConstructionProject_ProjectID"                          FOREIGN KEY ("ProjectID")              REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."Tranche"               ADD CONSTRAINT "FK_Tranche_ConstructionSite_ConstructionSiteID"                    FOREIGN KEY ("ConstructionSiteID")     REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."WBS"                   ADD CONSTRAINT "FK_WBS_ConstructionProject_ProjectID"                              FOREIGN KEY ("ProjectID")              REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."WBS"                   ADD CONSTRAINT "FK_WBS_ConstructionSite_ConstructionSiteID"                        FOREIGN KEY ("ConstructionSiteID")     REFERENCES "Data"."ConstructionSite" ("ID");
ALTER TABLE "Data"."WBSContract"           ADD CONSTRAINT "FK_WBSContract_ConstructionProject_ProjectID"                      FOREIGN KEY ("ProjectID")              REFERENCES "Data"."ConstructionProject" ("ID");
ALTER TABLE "Data"."WBSContract"           ADD CONSTRAINT "FK_WBSContract_ConstructionSite_ConstructionSiteID"                FOREIGN KEY ("ConstructionSiteID")     REFERENCES "Data"."ConstructionSite" ("ID");

-- Базовые индексы для частых выборок (ListView сортирует по ID DESC)
CREATE INDEX IF NOT EXISTS "IX_ConstructionProject_Hidden" ON "Data"."ConstructionProject" ("Hidden");
CREATE INDEX IF NOT EXISTS "IX_ConstructionSite_ProjectID" ON "Data"."ConstructionSite" ("ConstructionProjectID");
CREATE INDEX IF NOT EXISTS "IX_ConstructionSite_Hidden" ON "Data"."ConstructionSite" ("Hidden");
CREATE INDEX IF NOT EXISTS "IX_Room_SiteID" ON "Data"."Room" ("SiteID");
CREATE INDEX IF NOT EXISTS "IX_Room_KindID" ON "Data"."Room" ("KindID");
CREATE INDEX IF NOT EXISTS "IX_ShareAgreement_SiteID" ON "Data"."ShareAgreement" ("SiteID");
CREATE INDEX IF NOT EXISTS "IX_ConstructionSection_SiteID" ON "Data"."ConstructionSection" ("ConstructionSiteID");
