// <auto-generated />
using System;
using System.Text.Json;
using KiloImportService.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KiloImportService.Api.Migrations
{
    [DbContext(typeof(ImportServiceDbContext))]
    partial class ImportServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("import")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KiloImportService.Api.Data.Entities.ImportError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ColumnName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ImportSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportSessionId", "SourceRowNumber");

                    b.ToTable("import_errors", "import");
                });

            modelBuilder.Entity("KiloImportService.Api.Data.Entities.ImportFileSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImportSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ImportSessionId")
                        .IsUnique();

                    b.ToTable("import_file_snapshots", "import");
                });

            modelBuilder.Entity("KiloImportService.Api.Data.Entities.ImportSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("integer");

                    b.Property<string>("FileFormat")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FileSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ImportTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("SuccessRows")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("VisaryProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("VisarySiteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("ImportTypeCode", "FileSha256")
                        .IsUnique()
                        .HasDatabaseName("UX_ImportSession_TypeAndSha")
                        .HasFilter("\"Status\" NOT IN ('Failed','Cancelled')");

                    b.ToTable("import_sessions", "import");
                });

            modelBuilder.Entity("KiloImportService.Api.Data.Entities.ImportSessionStage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImportSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImportSessionId");

                    b.ToTable("import_session_stages", "import");
                });

            modelBuilder.Entity("KiloImportService.Api.Data.Entities.StagedRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AppliedTargetId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ImportSessionId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("MappedValues")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("RawValues")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ImportSessionId", "SourceRowNumber")
                        .IsUnique();

                    b.HasIndex("ImportSessionId", "Status");

                    b.ToTable("staged_rows", "import");
                });

            modelBuilder.Entity("KiloImportService.Api.Data.Entities.ImportError", b =>
                {
                    b.HasOne("KiloImportService.Api.Data.Entities.ImportSession", "Session")
                        .WithMany("Errors")
                        .HasForeignKey("ImportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("KiloImportService.Api.Data.Entities.ImportFileSnapshot", b =>
                {
                    b.HasOne("KiloImportService.Api.Data.Entities.ImportSession", "Session")
                        .WithOne("FileSnapshot")
                        .HasForeignKey("KiloImportService.Api.Data.Entities.ImportFileSnapshot", "ImportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("KiloImportService.Api.Data.Entities.ImportSessionStage", b =>
                {
                    b.HasOne("KiloImportService.Api.Data.Entities.ImportSession", "Session")
                        .WithMany("Stages")
                        .HasForeignKey("ImportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("KiloImportService.Api.Data.Entities.StagedRow", b =>
                {
                    b.HasOne("KiloImportService.Api.Data.Entities.ImportSession", "Session")
                        .WithMany("Rows")
                        .HasForeignKey("ImportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("KiloImportService.Api.Data.Entities.ImportSession", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("FileSnapshot");

                    b.Navigation("Rows");

                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
