DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'import') THEN
        CREATE SCHEMA import;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS import.__ef_migrations_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___ef_migrations_history" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'import') THEN
            CREATE SCHEMA import;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    CREATE TABLE import.import_sessions (
        "Id" uuid NOT NULL,
        "ImportTypeCode" character varying(64) NOT NULL,
        "FileName" character varying(500) NOT NULL,
        "FileSize" bigint NOT NULL,
        "FileFormat" character varying(8) NOT NULL,
        "FileSha256" character varying(64) NOT NULL,
        "Status" character varying(16) NOT NULL,
        "VisaryProjectId" integer,
        "VisarySiteId" integer,
        "UserId" character varying(128),
        "StartedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        "TotalRows" integer NOT NULL,
        "SuccessRows" integer NOT NULL,
        "ErrorRows" integer NOT NULL,
        "ErrorMessage" character varying(4000),
        CONSTRAINT "PK_import_sessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    CREATE TABLE import.import_errors (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ImportSessionId" uuid NOT NULL,
        "SourceRowNumber" integer NOT NULL,
        "ColumnName" character varying(255),
        "ErrorCode" character varying(64) NOT NULL,
        "Message" character varying(2000) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_import_errors" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_import_errors_import_sessions_ImportSessionId" FOREIGN KEY ("ImportSessionId") REFERENCES import.import_sessions ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    CREATE TABLE import.import_file_snapshots (
        "Id" uuid NOT NULL,
        "ImportSessionId" uuid NOT NULL,
        "RelativePath" character varying(500) NOT NULL,
        "ContentType" character varying(128) NOT NULL,
        "SizeBytes" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_import_file_snapshots" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_import_file_snapshots_import_sessions_ImportSessionId" FOREIGN KEY ("ImportSessionId") REFERENCES import.import_sessions ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    CREATE TABLE import.import_session_stages (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ImportSessionId" uuid NOT NULL,
        "Kind" character varying(16) NOT NULL,
        "StartedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        "ProgressPercent" integer NOT NULL,
        "Message" character varying(500),
        "IsSuccess" boolean NOT NULL,
        CONSTRAINT "PK_import_session_stages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_import_session_stages_import_sessions_ImportSessionId" FOREIGN KEY ("ImportSessionId") REFERENCES import.import_sessions ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    CREATE TABLE import.staged_rows (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ImportSessionId" uuid NOT NULL,
        "SourceRowNumber" integer NOT NULL,
        "RawValues" jsonb NOT NULL,
        "MappedValues" jsonb,
        "Status" character varying(16) NOT NULL,
        "AppliedTargetId" integer,
        CONSTRAINT "PK_staged_rows" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_staged_rows_import_sessions_ImportSessionId" FOREIGN KEY ("ImportSessionId") REFERENCES import.import_sessions ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    CREATE INDEX "IX_import_errors_ImportSessionId_SourceRowNumber" ON import.import_errors ("ImportSessionId", "SourceRowNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    CREATE UNIQUE INDEX "IX_import_file_snapshots_ImportSessionId" ON import.import_file_snapshots ("ImportSessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    CREATE INDEX "IX_import_session_stages_ImportSessionId" ON import.import_session_stages ("ImportSessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    CREATE INDEX "IX_import_sessions_StartedAt" ON import.import_sessions ("StartedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    CREATE INDEX "IX_import_sessions_Status" ON import.import_sessions ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    CREATE UNIQUE INDEX "UX_ImportSession_TypeAndSha" ON import.import_sessions ("ImportTypeCode", "FileSha256") WHERE "Status" NOT IN ('Failed','Cancelled');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    CREATE UNIQUE INDEX "IX_staged_rows_ImportSessionId_SourceRowNumber" ON import.staged_rows ("ImportSessionId", "SourceRowNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    CREATE INDEX "IX_staged_rows_ImportSessionId_Status" ON import.staged_rows ("ImportSessionId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM import.__ef_migrations_history WHERE "MigrationId" = '20260429084812_Initial') THEN
    INSERT INTO import.__ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260429084812_Initial', '9.0.4');
    END IF;
END $EF$;
COMMIT;

